severity: error
linters:
  BemDepth:
    enabled: true
    max_elements: 1
  Comment:
    enabled: false
  DisableLinterReason:
    enabled: true
  LeadingZero:
    style: include_zero
  NestingDepth:
    max_depth: 5
    severity: warning
  PlaceholderInExtend:
    severity: warning
  SelectorFormat:
    convention: hyphenated_BEM
  SingleLinePerProperty:
    allow_single_line_rule_sets: false
  StringQuotes:
    severity: warning
  TrailingZero:
    enabled: true
  TransitionAll:
    enabled: true
    severity: warning
  VariableForProperty:
    enabled: true
    properties:
      - font
      - font-family
      - font-size
      - font-weight
      - z-index
